export const FETCH_MASTER_DATA = 'FETCH_MASTER_DATA';
export const TOGGLE_MENU = 'TOGGLE_MENU';
export const FETCH_PRODUCT = 'FETCH_PRODUCT';
export const FETCH_DEALER = 'FETCH_DEALER';

// Purchase history
export const CREATE_PURCHASE = 'CREATE_PURCHASE';
export const ADD_PURCHASE = 'ADD_PURCHASE';
export const EDIT_PURCHASE = 'EDIT_PURCHASE';
export const FETCH_PURCHASE_LIST = 'FETCH_PURCHASE_LIST';
export const PURCHASE_TAG = 'PURCHASE_TAG';
export const CREATE_TAG = 'CREATE_TAG';
export const CREATE_TAG_ADDON = 'CREATE_TAG_ADDON';
export const EDIT_TAG_ADDON = 'EDIT_TAG_ADDON';
export const FETCH_TAG_DATA_BY_ID = 'FETCH_TAG_DATA_BY_ID';
export const DELETE_TAG_DATA_BY_ID = 'DELETE_TAG_DATA_BY_ID';
export const FETCH_TAG_LIST = 'FETCH_TAG_LIST';
export const CREATE_SALE = 'CREATE_SALE';